Re-target to netstandard2.0
digitaldjpool/intercom-dotnet pull request #1
Opened 2020-12-08 19:52 UTC by netspark

#### Why?
We need to have the library on dotnetcore

#### How?
Simple replace of the target framework and removal of the nuspec file

2020-12-08 20:02 UTC, seankearney commented on src/Intercom/Intercom.csproj
> +    <TargetFrameworks>netstandard2.0;</TargetFrameworks>
We've seen issues when targeting a single framework with the plural `TargetFrameworks`. I believe one targeting a single framework it should be `<TargetFramework>` (singular version).

2020-12-08 20:08 UTC, netspark commented
Here is what I get, if I change `TargetFrameworks` -> `TargetFramework`
![image](https://user-images.githubusercontent.com/706621/101535813-dae6aa80-39a1-11eb-82ce-46769a709875.png)

2020-12-08 20:13 UTC, seankearney requested changes

2020-12-08 20:13 UTC, seankearney commented on src/Intercom/Intercom.csproj
> +    <PackageId>Mdc.Intercom.DotNetCore</PackageId>
Let's leave the package name as-is. We can identify our custom fork with a version identifier

2020-12-08 20:13 UTC, seankearney commented on src/Intercom/Intercom.csproj
> +    <Summary>This is the full copy of the official Intercom API client library for .NET but published into NuGet feed</Summary>
`The digitaldjpool fork of the Intercom API client library for .NET Core`

2020-12-08 20:13 UTC, seankearney commented on src/Intercom/Intercom.csproj
> +    <Description>The fork of the official Intercom API client library for .NET with net standard support published into NuGet feed</Description>
`The fork of the official Intercom API client library for .NET Standard 2.0`

2020-12-08 20:13 UTC, seankearney commented on src/Intercom/Intercom.csproj
> +    <Version>3.1.0</Version>
Change this to `3.1.0-djp-01` which will indicate that this is a DJ Pool "pre-release" version of 3.1.0.

2020-12-08 20:30 UTC, seankearney commented
> Here is what I get, if I change `TargetFrameworks` -> `TargetFramework`
> ![image](https://user-images.githubusercontent.com/706621/101535813-dae6aa80-39a1-11eb-82ce-46769a709875.png)

That middle error is likely a result because of the trailing `;` Use `<TargetFramework>netstandard2.0</TargetFramework>`

2020-12-09 17:27 UTC, seankearney commented on src/Intercom/Intercom.csproj
> +    <Version>3.1.0</Version>
2.1.2-djp-01

2020-12-09 17:47 UTC, netspark commented
> 
> 
> > Here is what I get, if I change `TargetFrameworks` -> `TargetFramework`
> > ![image](https://user-images.githubusercontent.com/706621/101535813-dae6aa80-39a1-11eb-82ce-46769a709875.png)
> 
> That middle error is likely a result because of the trailing `;` Use `<TargetFramework>netstandard2.0</TargetFramework>`

This still gives me build errors even after stripping the `;`. It gives no errors for 
 `<TargetFrameworks>netstandard2.0</TargetFrameworks>`
@seankearney

2020-12-09 18:49 UTC, merged